spec:
  template:
    spec:
      containers:
        - resources:
            requests:
              memory: 128Mi
            limits:
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 2
